# Generated by Django 2.0.2 on 2018-02-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoicenumber',
            new_name='invoice_number',
        ),
    ]
